### PR TITLE
draft

### PR DESCRIPTION
**Pull request by michaelkerry**
The purpose of this module is to provide a standardized basic logging setup for python projects, as used in flask apis developed by aais.

Per request, INFO and DEBUG level messages will route to stdout; WARNING ERROR and CRITICAL will go to stderr

### CODE REVIEW

**Review by ccurreri — COMMENTED** [review]
Looks fine to me. The only thing I'd say is that technically you don't need the whole filter class objects these days. Any callable that takes a LogRecord and hands back a boolean.

**Comment by michaelkerry** [comment]
> Looks fine to me. The only thing I'd say is that technically you don't need the whole filter class objects these days. Any callable that takes a LogRecord and hands back a boolean.

Thanks Chris!

**Comment by michaelkerry** [comment]
Anyone care to approve the PR?

**Review by hapi-shams — APPROVED** [review]
Looks good

**Pull request merged**
